### ISSUE TITLE
Face recognition bug on iPhone XS

### ISSUE THREAD

**Issue by TikoyX** [AnalogIO/Analog_iOS#2]
Face recognition virker ikke på iPhone XS. 
Ved opstart prøver den at aflæse, det lykkedes og programmet lukkes.

**Comment by xthedeus** [comment]
Det virker på min telefon?
EDIT: sorry, jeg har ikke prøvet den refactored version. Jeg snakker bare om den nuværende appstore version :-)

**Comment by TikoyX** [comment]
Det er også den nuværende version fra app store. 
Det var en XS, men prøver lige at høre ham om det og få noget mere info omkring det. 
Har han mon prøvet den helt simple genstart / geninstaller (har de jo aldrig 🙄)

**Comment by xthedeus** [comment]
Jeg havde touch-id aktiveret fra tidligere telefon og jeg mener jeg blev nødt til at deaktivere “touch-id” i indstillinger og aktivere igen for at trigger face-id recognition. Lidt besværligt og klart noget der kan gøres nemmere.

**Comment by TikoyX** [comment]
OBS: den her bug er jo ligegyldig. Den kommer jo selvfølgelig ikke med i den nye app! 😄

**Comment by Frederikdam** [comment]
👍 👍
