### ISSUE TITLE
HomeTabBar orden

### ISSUE THREAD

**Issue by TikoyX** [AnalogIO/Analog_iOS#5]
Kunne det være en idé at lave ticket som den midterste, og så fremhæve den i anden farve? 
Når det alligevel er den man så ofte bruger

**Comment by Frederikdam** [comment]
Jeg foreslår at vi skal tage design ændringer op på Slack i "app-design" channel 👍 Vi kan oprette issues når designs er blevet approved tænker jeg ;)
